"""NOMBRE MIGRACION

Revision ID: 0ac683eed828
Revises: 8e07c9768920
Create Date: 2025-09-13 08:12:31.260954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac683eed828'
down_revision = '8e07c9768920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_3', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_4', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_5', sa.Float(), nullable=True))

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('price_5')
        batch_op.drop_column('price_4')
        batch_op.drop_column('price_3')
        batch_op.drop_column('price_2')

    # ### end Alembic commands ###
