"""NOMBRE MIGRACION

Revision ID: 110400468e07
Revises: 6d46bc41a5ad
Create Date: 2025-08-03 11:53:48.327074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '110400468e07'
down_revision = '6d46bc41a5ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('current_participants', sa.Integer(), nullable=False),
    sa.Column('price_1', sa.Float(), nullable=True),
    sa.Column('price_2', sa.Float(), nullable=True),
    sa.Column('price_3', sa.Float(), nullable=True),
    sa.Column('price_4', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('event_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('how_did_you_hear', sa.String(length=255), nullable=True),
    sa.Column('artistic_expression', sa.String(length=255), nullable=True),
    sa.Column('why_interested', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('price_paid', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('event_registrations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_registrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('how_did_you_hear', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('artistic_expression', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('why_interested', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('registration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('event_registrations_pkey'))
    )
    op.drop_table('event_participant')
    op.drop_table('event')
    # ### end Alembic commands ###
