"""MAILERLITE GROUP ID

Revision ID: 2dc5911d4e45
Revises: 5f4decc4ca83
Create Date: 2025-09-28 13:03:24.476717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc5911d4e45'
down_revision = '5f4decc4ca83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mailerlite_group_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('mailerlite_group_id')

    # ### end Alembic commands ###
