"""Initial database schema

Revision ID: 3c780174dfbb
Revises: 
Create Date: 2025-06-20 11:46:40.655545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c780174dfbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('event_name', sa.String(length=120), nullable=False),
    sa.Column('how_did_you_hear', sa.String(length=255), nullable=True),
    sa.Column('artistic_expression', sa.String(length=255), nullable=True),
    sa.Column('why_interested', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_registrations')
    # ### end Alembic commands ###
