"""Image Concent

Revision ID: 5f4decc4ca83
Revises: 0ac683eed828
Create Date: 2025-09-17 17:19:49.125238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4decc4ca83'
down_revision = '0ac683eed828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_conset', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participant', schema=None) as batch_op:
        batch_op.drop_column('image_conset')

    # ### end Alembic commands ###
