"""is read to events and contact added

Revision ID: 6d46bc41a5ad
Revises: 471a576099d8
Create Date: 2025-06-26 08:00:07.930268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d46bc41a5ad'
down_revision = '471a576099d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # --- Table: contact ---
    with op.batch_alter_table('contact', schema=None) as batch_op:
        # 1. Add the column as nullable=True with a server_default for initial population
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True, server_default=sa.text('false')))

    # 2. Update existing rows where is_read might be NULL (important for old data)
    # This must be an op.execute outside of batch_alter_table for direct SQL
    op.execute('UPDATE contact SET is_read = FALSE WHERE is_read IS NULL;')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        # 3. Alter the column to be NOT NULL and remove the server_default
        batch_op.alter_column('is_read',
           existing_type=sa.Boolean(),
           nullable=False, # Now it's truly NOT NULL
           existing_comment=None,
           server_default=None # Remove server-side default, let SQLAlchemy model handle it
        )

    # --- Table: event_registrations ---
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        # 1. Add the column as nullable=True with a server_default for initial population
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True, server_default=sa.text('false')))

    # 2. Update existing rows where is_read might be NULL
    op.execute('UPDATE event_registrations SET is_read = FALSE WHERE is_read IS NULL;')

    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        # 3. Alter the column to be NOT NULL and remove the server_default
        batch_op.alter_column('is_read',
           existing_type=sa.Boolean(),
           nullable=False, # Now it's truly NOT NULL
           existing_comment=None,
           server_default=None # Remove server-side default
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('is_read')
    # ### end Alembic commands ###