"""Reservation con checkout session

Revision ID: 8e07c9768920
Revises: e627a20d4ef8
Create Date: 2025-08-26 10:57:02.914222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e07c9768920'
down_revision = 'e627a20d4ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Paso 1: Renombrar las columnas existentes 'name' y 'email'
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('name', new_column_name='customer_name')
        batch_op.alter_column('email', new_column_name='customer_email')

    # Paso 2: Añadir las nuevas columnas requeridas como nullable=True para evitar errores
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('amount_paid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))

    # Paso 3: Actualizar los valores de las nuevas columnas si es necesario (en este caso, no es necesario porque son nulas)
    # Si 'customer_name' fuera nulo en alguna fila, el siguiente comando lo haría no nulo.
    op.execute("UPDATE reservation SET stripe_checkout_session_id = '' WHERE stripe_checkout_session_id IS NULL")
    op.execute("UPDATE reservation SET customer_name = '' WHERE customer_name IS NULL")
    op.execute("UPDATE reservation SET customer_email = '' WHERE customer_email IS NULL")
    op.execute("UPDATE reservation SET payment_status = '' WHERE payment_status IS NULL")


    # Paso 4: Cambiar las columnas a nullable=False si es necesario
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('customer_name', existing_type=sa.VARCHAR(length=120), nullable=False)
        batch_op.alter_column('customer_email', existing_type=sa.VARCHAR(length=120), nullable=False)
        batch_op.alter_column('payment_status', existing_type=sa.VARCHAR(length=50), nullable=False)
        # Nota: 'stripe_checkout_session_id', 'amount_paid' y 'currency' se quedan como nulos

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('payment_status')
        batch_op.drop_column('currency')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('stripe_checkout_session_id')
    # ### end Alembic commands ###