"""Added Event Priority

Revision ID: 98021f04b9a5
Revises: 110400468e07
Create Date: 2025-08-03 12:33:27.186650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98021f04b9a5'
down_revision = '110400468e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        # Paso 1: Añade la columna permitiendo valores nulos temporalmente
        batch_op.add_column(sa.Column('priority_order', sa.Integer(), nullable=True))

    # Paso 2: Actualiza todos los registros existentes para darles un valor por defecto
    # Esto llena los campos NULL y evita el error de NotNullViolation
    op.execute("UPDATE event SET priority_order = 999 WHERE priority_order IS NULL")

    with op.batch_alter_table('event', schema=None) as batch_op:
        # Paso 3: Modifica la columna para que ya no acepte valores nulos
        batch_op.alter_column('priority_order',
               existing_type=sa.INTEGER(),
               nullable=False)
               
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('priority_order')

    # ### end Alembic commands ###
