"""New Photo Path

Revision ID: acacfce30de5
Revises: d4cdfd7f445f
Create Date: 2025-08-17 12:34:46.123958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acacfce30de5'
down_revision = 'd4cdfd7f445f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('third_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('fourth_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('fifth_image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('fifth_image_url')
        batch_op.drop_column('fourth_image_url')
        batch_op.drop_column('third_image_url')
        batch_op.drop_column('second_image_url')

    # ### end Alembic commands ###
